- name: copying the mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: installing {{COMPONENT}}
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Replace value from 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting {{COMPONENT}}
  systemd:
        name: mongod
        state: restarted
        enabled: yes

- name: download and inject schema
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Inject MongoDB schema for users
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes

- name: Inject MongoDB schema for catalogue
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes




# - name: injecting mongodb schema       # for loop also we can use
#   community.mongodb.mongodb_shell:
#     file: "/tmp/mongodb-main/{{item}}.js"
#     idempotent: yes
#   loop:
#     - users
#     - catalogue

- name: configuring {{COMPONENT}} name
  ansible.builtin.include_role:
    name: common 
    tasks_from: name-update
