- name: demo on condition
  hosts: all
  vars: 
    action: false
  tasks:
    - name: runs only if distribution is CentOS
      ansible.builtin.debug:
        msg: "Welcome to CentOS {{ansible_distribution}}"
      when: ansible_distribution == "CentOS"

    - name: runs only if distribution is REDHAT
      ansible.builtin.debug:
        msg: "Welcome to Red Hat {{ansible_distribution}}"
      when: ansible_distribution == "RedHat"
