- name: demo on condition
  hosts: all
  tasks: 
     - name: runs only if distribution iss centos
       ansible.buildin.debug:
         msg: welcome to centos {{ansible_distribution}}
       when: ansible_distribution == "centos"  

     - name: runs only if distribution is REDHAT
       ansible.buildin.debug:
        msg: welcome to centos {{ansible_distribution}}
       when: ansible_distribution == "REDHAT"    