- name: demo on facts
  hosts: all
  gather_facts: yes
  tasks: 
    - name: printing the default variable
      ansible.builtin.debug:
        msg: server flavour is "{{ansible_distribution_file_variety}}"