---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: "t3.micro"
    security_group_id: "sg-0114a25a2a35f75d8"  # Update with your security group ID
    image: "ami-0d3eb821da112abf4"            # Update with your AMI ID
    region: "us-east-1"            # Update with your key pair name            # Update with your subnet ID
    ec2_tags:
      Name: "MyEC2Instance"                   # Customize your EC2 instance name tag
  tasks:
      name: Launching EC2 instance
      ec2:
        aws_access_key: "{{ access_key }}"    # Update with your AWS access key
        aws_secret_key: "{{ secret_key }}"    # Update with your AWS secret key
        region: "{{ region }}"
        image: "{{ image }}"
        instance_type: "{{ instance_type }}"
        security_groups: "{{ security_group_id }}"
        subnet_id: "{{ subnet_id }}"
        instance_tags: "{{ ec2_tags }}"
        wait: yes
      register: ec2_instance

    - name: Display EC2 instance information
      debug:
        var: ec2_instance.instances[0].public_ip  # Display the public IP of the launched instance
