---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: "t3.micro"
    security_group_id: "sg-0114a25a2a35f75d8"  # Update with your security group ID
    image: "ami-0d3eb821da112abf4"            # Update with your AMI ID
    region: "us-east-1"
    ec2_tags:
      Name: "MyEC2Instance"                   # Customize your EC2 instance name tag
  tasks:
    - name: Launching EC2 instance
      community.aws.ec2_instance:
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        security_group: "{{ security_group_id }}"
        instance_tags:
          Name: "{{ ec2_tags.Name }}"
        wait: yes
      register: ec2_instance

    - name: Display EC2 instance information
      debug:
        var: ec2_instance.instances[0].public_ip  # Display the public IP of the launched instance
