- name: Creating EC2 for DryRun
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: "t3.micro"
    security_group_id: "sg-0efe0f01b32f1d318"  # Update as per your security group id
    image: "ami-0edcd33c11a89dfa6"             # Update this with the AMI ID in your account which has ansible installed.
    region: "us-east-1"
  tasks:
    - name: Launching instance
      community.aws.ec2:
         count: 1
         group_id: "{{ security_group_id }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         instance_tags:
          Name: ansible-dryrun
      register: ec2

    # Other tasks...

- name: Run Role to Test
  hosts: launched
  become: True
  gather_facts: Yes
  tasks:
    # Role tasks...

# Ansible is not a right tool for provisioning infrastructure. Terraform is the right way to provision the infrastructure. But just consider it for understanding the test case.
