- name: Creating EC2 for DryRun
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: "t3.micro"
    security_group_id: "sg-0114a25a2a35f75d8"  # Update as per your security group id
    image: "ami-0d3eb821da112abf4"             # Update this with the AMI ID in your account which has ansible installed.
    region: "us-east-1"
  tasks:
    - name: Launching instance
      amazon.aws.ec2:
        count: 1
        group_id: "{{ security_group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        instance_tags:
          Name: ansible-dryrun
      register: ec2

  - name: Adding instance to the host group and waiting for SSH
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: launched
    loop: "{{ ec2.instances }}"

- name: Run Role to Test
  hosts: launched
  become: True
  gather_facts: Yes
  tasks:
    - name: Import the role and Terminate the instance
      block:
        - name: Import a role (Replace 'COMPONENT' with actual role name)
          import_role:
            name: "{{ COMPONENT }}"
      always:
        - name: Set a Instance_ID Variable
          set_fact:
            INSTANCE_ID: "{{ hostvars['localhost']['ec2']['instances'][0]['instance_id'] }}"
        - name: Terminate instances that were previously launched
          amazon.aws.ec2:
            state: 'absent'
            instance_ids: '{{ INSTANCE_ID }}'
            region: us-east-1
