- name: demo on shell
  hosts: all
  tasks: 
    - name: running uptime command
      ansible.builtin.shell: uptime
      register: OUT
       
    - name: printing the uptime
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"   

    - name: declaring the variable
      set_fact:
        EXITCODE: "{{OUT.rc}}"    

    - name: printing the uptime exit code
      ansible.builtin.debug:
        msg: uptime exit code is {{EXITCODE}}    