---
- name: demo on vars
  hosts: all
  vars: 
    URL: play.google.com
  vars_files: 
    - "{{ENV}}.yml"

  tasks:
    - name: printing HAI from task1 of play1
      ansible.builtin.debug:
        msg: value of {{URL}}

    - name: printing HAI from task2 of play1
      ansible.builtin.debug:
        msg: Devops from the {{URL}}
      vars:
        URL: cloudkid
    
    - name: printing HAI from task1 of play3
      ansible.builtin.debug:
        msg: value of {{URL}}

    - name: printing the env specific
      ansible.builtin.debug:
       msg: type of instance is {{INS_TYPE}}