
- name: Installing maven on {{COMPONENT}}-{{ENV}} server
  ansible.builtin.package:
    name: java  # Removed the list structure around 'name'
    state: present

- name: creating  {{APPUSER}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: create_user

- name: configuring {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download_and_extractlink

- name: genearting artifacts
  community.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/
- name: configuring config and naming 
  ansible.builtin.include_role:
    name: common 
    tasks_from: config_service
