
- name: Configuring Node.js Repository
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_16.x | bash - 

- name: Installing Node.js
  ansible.builtin.package:
    name: nodejs  # Removed the list structure around 'name'
    state: present

- name: creating  {{APPUSER}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: create_user.yml

- name: configuring {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download_and_extractlink

- name: genearting artifacts
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: configuring config and naming 
  ansible.builtin.include_role:
    name: common 
    tasks_from: config_service
